### PR TITLE
Bootstrapping

### PR DESCRIPTION
**Pull request by nmaquet**
WIP

### CODE REVIEW

**Comment by nmaquet** [comment]
@echojc I got a basic version of bootstrapping working. Still to do:
- figure out when to lock / unlock the table
- figure out when / how to replay the binlog since bootstrapping as started
- add unit tests / integration tests
- refactor code
- make sure all column types are supported
- do performance testing with large tables

**Comment by nmaquet** [comment]
@osheroff We're not quite done yet but this is our first go. If you've got time, would you mind having a look and tell us whether we're on the right track? In particular:
- What do you think about the async processing model we went for? Is one thread for bootstrapping enough or should we have more?
- Are you happy with the code style?
- Are you happy with the way bootstrapping is integrated with argv options and the config file?
- We're not quite sure how to best implement the binlog replay... any pointers here would be helpful.

**Comment by osheroff** [comment]
@nmaquet, overall this looks like a great start.  Code style is good, async is good.  Having a configurable # of bootstrapping threads would be good, but not necessary for a first pass.

At first I was a little unsure about the use of the `maxwell`.`bootstrap` table - and the replication stream - as an API channel to control maxwell; it wasn't immediately obvious from the code what was going on.  The more I think about tnough, the more I like it -- Maxwell really only has one input bus while it's live, and doing it this method is better than slapping a stupid HTTP api on the daemon.  So cool!  Some notes about this:
1. It'd be good to supply a dumb-simple 'maxwell-bootstrap' script (doesn't have to be java necessarily, even a wrapper around the `mysql` util would be fine) that can do some basic schema discovery and create these rows, as well as report progress on how far along the bootstrap is, etc.  ie we should wrap the database-as-bus trick in something prettier.
2. I think it could be made clearer, either in the naming of things, or maybe just in judicious commenting, what exactly we're doing with the `boostrap` table, and the replication stream, and why.
3.  Have you thought about how you might resume an interrupted bootstrap?  From a shallow reading of the code it looks like the following is possible:

```
  - read bootstrap row, start 
  - MaxwellReplicator continues on
  - crash, or SIGTERM, or whatever
  - now the bootstrapping effort is lost
```

re: 

> We're not quite sure how to best implement the binlog replay... any pointers here would be helpful.

Probably the simplest thing to do is to simply buffer the `RowMap` items to memory/disk while you're bootstrapping.  See `RowMapBuffer` and the underlying `ListWithDiskBuffer` class, although I think there's still a memory leak in there somewhere....

**Comment by osheroff** [comment]
(ps, inspired me to go find the memory leak.  https://github.com/zendesk/maxwell/pull/202)

**Comment by nmaquet** [comment]
@osheroff Thanks again for the feedback.

> It'd be good to supply a dumb-simple 'maxwell-bootstrap' script

That will be really useful, we'll do that.

> I think it could be made clearer, either in the naming of things, or maybe just in judicious 
> commenting, what exactly we're doing with the boostrap table, and the replication stream, and why.

Agreed, that part can definitely be confusing at first glance. I'll add a section in the docs that explains exactly how the bootstrap table is used and what is written to the replication stream.

> Have you thought about how you might resume an interrupted bootstrap?

This is currently rather crudely handled by the `resume()` method, which simply restarts the bootstrap from the beginning. Do you think it is worth hedging further against interrupted bootstraps?

**Comment by osheroff** [comment]
oh ok, I missed the `resume` method.  At some point it might be nice to track how far along you've gotten in a table (I guess keep id ranges, assuming auto-increment?) but this is also fine for a v1.

**Comment by nmaquet** [comment]
> At some point it might be nice to track how far along you've gotten in a table (I guess keep id ranges, assuming auto-increment?) but this is also fine for a v1.

Got it, thanks.

**Comment by nmaquet** [comment]
@osheroff The code is now ready for review.
- async bootstrapping is now fully implemented including queuing and replay of binlog events
- added a `maxwell-bootstrap` command-line utility
- added a section on bootstrapping in the docs
- added integration tests
- added comments

Please tell me if there's anything else we can do to help with merging this in upstream.

**Comment by nmaquet** [comment]
@osheroff Just one question: I removed one line of code in MaxwellReplicator.java that was setting the timezone to UTC. I couldn't understand why this was needed and since it was causing issues in testing I elected to remove it. Can you confirm this is OK?

**Comment by nmaquet** [comment]
moving the PR to zendesk/maxwell: https://github.com/zendesk/maxwell/pull/217

**Pull request closed without merging**
